from __future__ import annotations


class ErrorCodes:
    class TECH:
        VALIDATION_REQUIRED = "TECH.VALIDATION.REQUIRED"
        VALIDATION_INVALID = "TECH.VALIDATION.INVALID"
        VALIDATION_FORMAT = "TECH.VALIDATION.FORMAT"

        AUTH_INVALID_CREDENTIALS = "TECH.AUTH.INVALID_CREDENTIALS"
        AUTH_TOKEN_EXPIRED = "TECH.AUTH.TOKEN_EXPIRED"
        AUTH_TOKEN_INVALID = "TECH.AUTH.TOKEN_INVALID"
        AUTH_UNAUTHORIZED = "TECH.AUTH.UNAUTHORIZED"

        RATE_LIMIT_TOO_MANY_REQUESTS = "TECH.RATE_LIMIT.TOO_MANY_REQUESTS"
        CONFLICT = "TECH.CONFLICT"
        NOT_FOUND = "TECH.NOT_FOUND"
        INTERNAL = "TECH.INTERNAL"

    class DOMAIN:
        USER_ALREADY_EXISTS = "DOMAIN.USER.ALREADY_EXISTS"
        USER_INACTIVE = "DOMAIN.USER.INACTIVE"
        USER_NOT_FOUND = "DOMAIN.USER.NOT_FOUND"
